#!/usr/bin/env node
'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
const readline = require('node:readline/promises');
const { stdin, stdout } = require('node:process');
const { createPasswordHash } = require('../lib/auth');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, '.joblio-data');
const configPath = path.join(dataDir, 'config.env');
const tlsDirCert = path.join(dataDir, 'tls', 'localhost-cert.pem');
const tlsDirKey = path.join(dataDir, 'tls', 'localhost-key.pem');

function randHex(bytes) {
  return crypto.randomBytes(bytes).toString('hex');
}

function parseBool(v, fallback = false) {
  if (v == null || v === '') return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(v).trim().toLowerCase());
}

function parsePort(v, fallback = 8787) {
  const n = Number(v);
  if (!Number.isInteger(n) || n < 1 || n > 65535) return fallback;
  return n;
}

function isValidTlsMode(v) {
  return new Set(['off', 'on', 'require']).has(v);
}

async function promptHidden(promptText) {
  return new Promise((resolve) => {
    const input = stdin;
    const output = stdout;
    let value = '';
    output.write(promptText);
    input.setRawMode(true);
    input.resume();
    input.setEncoding('utf8');
    const onData = (char) => {
      if (char === '\u0003') {
        output.write('\n');
        process.exit(130);
      }
      if (char === '\r' || char === '\n') {
        input.setRawMode(false);
        input.pause();
        input.removeListener('data', onData);
        output.write('\n');
        resolve(value);
        return;
      }
      if (char === '\u007f' || char === '\b' || char === '\u0008') {
        value = value.slice(0, -1);
        return;
      }
      value += char;
    };
    input.on('data', onData);
  });
}

async function interactiveSetup(force) {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    const userRaw = await rl.question('Basic auth username [joblio]: ');
    const user = String(userRaw || 'joblio').trim() || 'joblio';
    const pass = await promptHidden('Basic auth password (min 12 chars): ');
    const pass2 = await promptHidden('Confirm password: ');
    if (pass !== pass2) throw new Error('Password confirmation did not match.');
    if (pass.length < 12) throw new Error('Password must be at least 12 characters.');

    const hostRaw = await rl.question('Host [127.0.0.1]: ');
    const host = String(hostRaw || '127.0.0.1').trim() || '127.0.0.1';
    const portRaw = await rl.question('Port [8787]: ');
    const port = parsePort(portRaw, 8787);

    const allowRemote = parseBool(await rl.question('Allow remote binding? (y/N): '), false) ? '1' : '0';
    const hasLocalTls = fs.existsSync(tlsDirCert) && fs.existsSync(tlsDirKey);
    const tlsDefault = hasLocalTls ? 'require' : 'off';
    const tlsModeRaw = await rl.question(`TLS mode [${tlsDefault}] (off/on/require): `);
    const tlsMode = String(tlsModeRaw || tlsDefault).trim().toLowerCase();
    if (!isValidTlsMode(tlsMode)) throw new Error('TLS mode must be off, on, or require.');

    return { user, pass, host, port, allowRemote, tlsMode, force };
  } finally {
    rl.close();
  }
}

function nonInteractiveSetup(force) {
  const user = String(process.env.JOBLIO_SETUP_USER || '').trim() || 'joblio';
  const pass = String(process.env.JOBLIO_SETUP_PASSWORD || '');
  if (!pass) throw new Error('Non-interactive setup requires JOBLIO_SETUP_PASSWORD.');
  if (pass.length < 12) throw new Error('JOBLIO_SETUP_PASSWORD must be at least 12 characters.');
  const host = String(process.env.JOBLIO_SETUP_HOST || process.env.HOST || '127.0.0.1').trim() || '127.0.0.1';
  const port = parsePort(process.env.JOBLIO_SETUP_PORT || process.env.PORT, 8787);
  const allowRemote = parseBool(process.env.JOBLIO_SETUP_ALLOW_REMOTE, false) ? '1' : '0';
  const defaultTls = (fs.existsSync(tlsDirCert) && fs.existsSync(tlsDirKey)) ? 'require' : 'off';
  const tlsMode = String(process.env.JOBLIO_SETUP_TLS_MODE || defaultTls).trim().toLowerCase();
  if (!isValidTlsMode(tlsMode)) throw new Error('JOBLIO_SETUP_TLS_MODE must be off, on, or require.');
  return { user, pass, host, port, allowRemote, tlsMode, force };
}

function toEnvValue(v) {
  return String(v).replace(/\n/g, '').replace(/\r/g, '');
}

async function writeConfig(setup) {
  await fsp.mkdir(dataDir, { recursive: true, mode: 0o700 });
  const hash = createPasswordHash(setup.pass);
  const tlsMode = setup.tlsMode;
  const tlsCertPath = process.env.JOBLIO_SETUP_TLS_CERT_PATH || tlsDirCert;
  const tlsKeyPath = process.env.JOBLIO_SETUP_TLS_KEY_PATH || tlsDirKey;
  const lines = [
    '# Joblio managed configuration file',
    '# Generated by npm run setup',
    `HOST=${toEnvValue(setup.host)}`,
    `PORT=${toEnvValue(setup.port)}`,
    `JOBLIO_ALLOW_REMOTE=${toEnvValue(setup.allowRemote)}`,
    'JOBLIO_STRICT_MODE=1',
    `JOBLIO_API_TOKEN=${toEnvValue(process.env.JOBLIO_SETUP_API_TOKEN || randHex(32))}`,
    `JOBLIO_BASIC_AUTH_USER=${toEnvValue(setup.user)}`,
    `JOBLIO_BASIC_AUTH_HASH=${toEnvValue(hash)}`,
    `JOBLIO_AUDIT_KEY=${toEnvValue(process.env.JOBLIO_SETUP_AUDIT_KEY || randHex(32))}`,
    `JOBLIO_TLS_MODE=${toEnvValue(tlsMode)}`,
    `JOBLIO_TLS_CERT_PATH=${toEnvValue(tlsCertPath)}`,
    `JOBLIO_TLS_KEY_PATH=${toEnvValue(tlsKeyPath)}`,
    `JOBLIO_COOKIE_SECURE=${tlsMode === 'off' ? '0' : '1'}`,
    'JOBLIO_SESSION_BINDING=strict',
    'JOBLIO_HEALTH_VERBOSE=0',
    'JOBLIO_ERROR_VERBOSE=0',
    '',
  ];
  const tmp = `${configPath}.tmp`;
  await fsp.writeFile(tmp, lines.join('\n'), { mode: 0o600 });
  await fsp.rename(tmp, configPath);
  await fsp.chmod(configPath, 0o600).catch(() => {});
}

async function main() {
  const force = parseBool(process.env.JOBLIO_SETUP_FORCE, false) || process.argv.includes('--force');
  const nonInteractive = parseBool(process.env.JOBLIO_SETUP_NON_INTERACTIVE, false);
  const configExists = fs.existsSync(configPath);

  if (configExists && !force) {
    console.log('Setup complete: existing configuration found.');
    process.exit(0);
  }

  const canPrompt = Boolean(stdin.isTTY && stdout.isTTY) && !nonInteractive;
  const setup = canPrompt ? await interactiveSetup(force) : nonInteractiveSetup(force);
  await writeConfig(setup);
  console.log('Setup complete: configuration saved to .joblio-data/config.env');
}

main().catch((err) => {
  console.error(`Setup failed: ${err?.message || String(err)}`);
  process.exit(1);
});
